stages:
  - build
  - style
  - test

build-job:
  stage: build
  tags:
    - build
  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: "30 days"

style-job:
  stage: style
  tags:
    - style

  script:
    - cd src
    - clang-format -n --style=Google cat/*.c cat/*.h grep/*.c grep/*.h
    - clang-format -i --style=Google cat/*.c cat/*.h grep/*.c grep/*.h
    - git diff --exit-code

test-job:
  stage: test
  tags:
    - test

  script:
    - cd src/cat
    - make s21_cat
    - cd ../grep
    - make s21_grep

    - cd ..
    - chmod +x cat/diffcat.sh grep/diffgrep.sh

    - cat/diffcat.sh | tee cat/cat-test.txt
    - grep/diffgrep.sh | tee grep/grep-test.txt

    - if grep -q differ cat/cat-test.txt; then exit 1; fi
    - if grep -q differ grep/grep-test.txt; then exit 1; fi
